### ISSUE TITLE
Update jsonwebtoken dep to 8.0 due to RUSTSEC-2020-0159

### ISSUE THREAD

**Issue by maxlambrecht** [nhynes/jwk-rs#10]
Version 8.0 of `jsonwebtoken` removes `chrono` and uses `time` crate directly, due to [RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159).

**Comment by nhynes** [comment]
`0.3.5` is out now with #7 included. Thanks for your patience.
